# Generated by Django 5.0.7 on 2024-07-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Название')),
                ('url', models.URLField(max_length=250, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='youtube_images/', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Ютуб видео',
                'verbose_name_plural': 'Ютуб видео',
                'db_table': 'youtube_video',
            },
        ),
    ]
